// /src/types/events.ts
export const CLIENT_EVENTS = {
    SEND_MESSAGE: 'SEND_MESSAGE',
    EDIT_MESSAGE: 'EDIT_MESSAGE',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
    ADD_REACTION: 'ADD_REACTION',
    REMOVE_REACTION: 'REMOVE_REACTION',
    START_TYPING: 'START_TYPING',
    STOP_TYPING: 'STOP_TYPING',
    FETCH_MESSAGES: 'FETCH_MESSAGES',
    JOIN_CHANNEL: 'JOIN_CHANNEL',
    LEAVE_CHANNEL: 'LEAVE_CHANNEL',
    UPLOAD_MEDIA: 'UPLOAD_MEDIA',
    MARK_AS_READ: 'MARK_AS_READ',
    PING: 'PING'
  } as const;
  
  export const SERVER_EVENTS = {
    MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
    MESSAGE_EDITED: 'MESSAGE_EDITED',
    MESSAGE_DELETED: 'MESSAGE_DELETED',
    REACTION_ADDED: 'REACTION_ADDED',
    REACTION_REMOVED: 'REACTION_REMOVED',
    TYPING_STARTED: 'TYPING_STARTED',
    TYPING_STOPPED: 'TYPING_STOPPED',
    USER_JOINED: 'USER_JOINED',
    USER_LEFT: 'USER_LEFT',
    USER_STATUS_CHANGED: 'USER_STATUS_CHANGED',
    READ_RECEIPT_UPDATED: 'READ_RECEIPT_UPDATED',
    MEDIA_UPLOADED: 'MEDIA_UPLOADED',
    MESSAGES_LOADED: 'MESSAGES_LOADED',
    CHANNEL_CREATED: 'CHANNEL_CREATED',
    NEW_DM_INVITE: 'NEW_DM_INVITE',
    PONG: 'PONG',
    ERROR: 'ERROR',
    CONNECTION: 'CONNECTION'
  } as const;
  
  export type ClientEvent = keyof typeof CLIENT_EVENTS;
  export type ServerEvent = keyof typeof SERVER_EVENTS;